#!/usr/bin/python3

import sys


def factorize(n):
    factors = []
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            factors.append((i, n//i))
    return factors


def main(file_name):
    with open(file_name, 'r') as f:
        for line in f:
            n = int(line.strip())
            factors = factorize(n)
            if factors:
                for factor in factors:
                    print(f"{n}={factor[0]}*{factor[1]}")
            else:
                print(f"{n} is prime")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    file_name = sys.argv[1]
    main(file_name)
